# Generated by Django 6.0.7 on 2026-07-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accelerator_name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple choice'), ('video', 'Video')], max_length=20)),
                ('original_text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('problem', 'Problem'), ('solution', 'Solution'), ('why_now', 'Why now'), ('why_you', 'Why you'), ('team', 'Team'), ('traction', 'Traction'), ('business_model', 'Business model'), ('market_size', 'Market size'), ('competition', 'Competition'), ('moat', 'Moat'), ('gtm', 'GTM'), ('product_demo', 'Product demo'), ('tech', 'Tech'), ('milestones', 'Milestones'), ('ask', 'Ask'), ('use_of_funds', 'Use of funds'), ('risks', 'Risks'), ('failure_story', 'Failure story'), ('why_this_program', 'Why this program'), ('legal_admin', 'Legal admin'), ('other', 'Other')], max_length=30, null=True)),
                ('max_chars', models.IntegerField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('focus', models.CharField(blank=True, choices=[('founder_intro', 'Founder intro'), ('pitch', 'Pitch'), ('demo', 'Demo')], max_length=20, null=True)),
                ('min_seconds', models.IntegerField(blank=True, null=True)),
                ('max_seconds', models.IntegerField(blank=True, null=True)),
                ('orientation', models.CharField(choices=[('h', 'Horizontal'), ('v', 'Vertical'), ('any', 'Any')], default='any', max_length=5)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('any', 'Any')], default='any', max_length=5)),
                ('who', models.CharField(choices=[('solo', 'Solo'), ('all_founders', 'All founders'), ('any', 'Any')], default='any', max_length=15)),
                ('accelerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aplicator.accelerator')),
            ],
        ),
    ]
