# Generated by Django 6.0.7 on 2026-07-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicator', '0002_accelerator_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('problem', 'Problem'), ('solution', 'Solution'), ('why_now', 'Why now'), ('why_you', 'Why you'), ('team', 'Team'), ('traction', 'Traction'), ('business_model', 'Business model'), ('market_size', 'Market size'), ('competition', 'Competition'), ('moat', 'Moat'), ('gtm', 'GTM'), ('product_demo', 'Product demo'), ('tech', 'Tech'), ('milestones', 'Milestones'), ('ask', 'Ask'), ('use_of_funds', 'Use of funds'), ('risks', 'Risks'), ('failure_story', 'Failure story'), ('why_this_program', 'Why this program'), ('legal_admin', 'Legal admin'), ('other', 'Other')], max_length=30, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicator.question')),
            ],
        ),
    ]
