# Generated by Django 6.0.7 on 2026-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicator', '0003_canonicalanswer_generatedanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelerator',
            name='accelerator_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
